[versions]
# Plugins
kotlin = "1.8.22"
android = "8.1.2"
dokka = "1.8.20"
versionUpdater = "0.49.0"
ktlint = "11.6.1"
mavenRelease = "0.25.3"
moshiIR = "0.22.1"

# AndroidX libraries
compatLibrary = "1.6.1"
androidxActivity = "1.8.0"
annotationsLibrary = "1.7.0"
fragmentLibrary = "1.6.2"
materialLibrary = "1.10.0"
lifecycleLibrary = "2.6.2"
prefsLibrary = "1.2.1"
multidex = "2.0.1"

# Third party Libraries
facebookLogin = "16.2.0"
googlePlayServices = "20.7.0"
retrofit = "2.9.0"
okhttp = "4.12.0"
moshi = "1.15.0"
timber = "5.0.1"
pianoConsents = "1.0.0"
cxense = "2.5.0"
coroutines = "1.7.3"

# Test Libraries
junit = "4.13.2"
androidxTestCore = "1.5.0"
androidxTestExtJunit = "1.1.5"
mockitoKotlin = "2.2.0"
mockitoCore = "3.12.1"

[plugins]
mavenRelease = { id = "com.vanniktech.maven.publish", version.ref = "mavenRelease" }
moshiIR = { id = "dev.zacsweers.moshix", version.ref = "moshiIR"}

[libraries]
annotations = { module = "androidx.annotation:annotation", version.ref = "annotationsLibrary" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "compatLibrary" }
androidxActivity = { module = "androidx.activity:activity", version.ref = "androidxActivity" }
fragments = { module = "androidx.fragment:fragment", version.ref = "fragmentLibrary" }
material = { module = "com.google.android.material:material", version.ref = "materialLibrary" }
lifecycleCommon = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycleLibrary" }
multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }
facebookLogin = { module = "com.facebook.android:facebook-login", version.ref = "facebookLogin" }
googleAuth = { module = "com.google.android.gms:play-services-auth", version.ref = "googlePlayServices" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofitConverter = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttpLogging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
prefsKtx = { module = "androidx.preference:preference-ktx", version.ref = "prefsLibrary" }
lifecycleKtx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleLibrary" }
pianoConsents = { module = "io.piano.android:consents", version.ref = "pianoConsents" }
cxense = { module = "io.piano.android:cxense", version.ref = "cxense" }
kotlinCoroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

kotlinJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
mockitoKotlin = { module = "com.nhaarman.mockitokotlin2:mockito-kotlin", version.ref = "mockitoKotlin" }
mockitoCore = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
junit = { module = "junit:junit", version.ref = "junit" }
androidxTestCore = { module = "androidx.test:core-ktx", version.ref = "androidxTestCore" }
androidxTestExtJunit = { module = "androidx.test.ext:junit-ktx", version.ref = "androidxTestExtJunit" }
okhttpMockServer = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }
